### DISCUSSION TITLE
Array property being generated as tuple?

### DISCUSSION THREAD

**Discussion by haggs** [openapi-ts/openapi-typescript#1452] [Q&A]
It's probably easiest to understand my issue when looking at my code, but it appears openapi-typescript (6.7.0) is generating a property as a tuple instead of as an array. Anyone know what I should do?

```yaml
# ChatRequest.yaml
type: object
required: 
  -  chat_context
properties:
  chat_context:
    type: array
    items:
    - $ref: './ChatEntry.yaml'

# ChatEntry.yaml
type: object
required: [role, content]
properties:
  role:
    type: string
    enum: [ "user", "assistant"]
  content:
    type: string
    minLength: 1
    maxLength: 30000
```

```typescript
export type ChatEntry = external["ChatEntry.yaml"];
export type ChatRequest = external["ChatRequest.yaml"];

const chatContext: ChatEntry[] = getChatContext();

/*
 TS throws this error:
 Type '{ role: "user" | "assistant"; content: string; }[]' is not assignable to type '[{ role: "user" | "assistant"; content: string; }]'.
  Target requires 1 element(s) but source may have fewer.ts(2322)
  The expected type comes from property 'chat_context' which is declared here on type '{ chat_context: [{ role: "user" | "assistant"; content: string; }]; }'
 */
const body: ChatRequest = {
  chat_context: chatContext
}
```
