### DISCUSSION TITLE
How to convert params in format "string with dots" to nested objects?

### DISCUSSION THREAD

**Discussion by iksent** [openapi-ts/openapi-typescript#1531] [General]
I have a query and parameters with keys, containing multiples keys inside, take a look at Swagger and result generated scheme:

<img src="https://github.com/drwpow/openapi-typescript/assets/32956521/f7275115-300f-4fef-9c72-003c52c9141b" width="40%"/>

<img src="https://github.com/drwpow/openapi-typescript/assets/32956521/6ff04130-76fe-49dc-89db-af2d4777e2bc" width="40%"/>

Please advise, how to get it in the next format with nested objects in a query?

<img width="292" alt="image" src="https://github.com/drwpow/openapi-typescript/assets/32956521/abbab2f6-adfa-4ae3-9298-25913f22745f">

**Comment by radist2s** [comment]
Seems, you have to change your Open API Schema according to the nesting you are expecting to see generated.

```yaml
parameters:
- in: path
  name: Filters
  schema:
    type: object
    properties:
      ThemeId:
        type: number
      # other props...
```
In case your backend responds with the data schema you have provided, and you are not able to change Open API Schema (third party, for example), you have to apply some preprocessing on your source Open API schema and then use it with the `openapi-typescript` .
