### DISCUSSION TITLE
undefined type yields `unknown` - can it yield `never` instead?

### DISCUSSION THREAD

**Discussion by hesxenon** [openapi-ts/openapi-typescript#2028] [Q&A] [answered]
Sometimes specs aren't properly written and e.g.
```yaml
      parameters:
        - in: query
          name: foo
          schema:
            type: array
            description: foos
```
transforms to
`unknown[]` - which allows to pass any items. I think it would be better if that was typed as `never[]`, so that we could notice such errors.

Is there already a way to achieve this or should I open an issue?
