### ISSUE TITLE
What's the recommended way of defining a number parameter in a path?

### ISSUE THREAD

**Issue by Enome** [openapi-ts/openapi-typescript#1353]
I have the spec:

```
/companies/{company_id}:
  get:
    summary: Show company
    tags:
      - Company
    security:
      - oat: []
    parameters:
      - in: path
        name: company_id
        schema:
          type: string
        required: true
    ...
```

Which will generate the following:

```
[path: `/companies/${number}`]: {
  /** Show company */
  get: {
    parameters: {
      path: {
        company_id: number;
      };
    };
   ...
  };
```

Following the examples in the docs I was expecting to be able to do this:

```
await api.DELETE(`/companies/{company_id}`,  {
  params: { path: { company_id: 1 } },
});
```

This made typescript complain about the path being passed to DELETE(), so after looking at the type definitions I realized it's expecting a number.

So then I did this:

```
await api.DELETE(`/companies/1`,  {
  params: { path: { company_id: 1 } },
});
```

So this works but it feels kinda weird having the set the company_id twice. So I was wondering if maybe I am missing something or is this the way it's supposed to work?
