### ISSUE TITLE
Array of Enum with --enum--values creates 2-D Type, but 1-D values

### ISSUE THREAD

**Issue by lucider5** [openapi-ts/openapi-typescript#1856]
The generated --enum--values schema.ts file creates a 2-D Type and 1-D values.

**Spec:**
```
someList:
  type: array
  items:
    type: string
    enum:
    - One
    - Two
    - Three
```

**Schema File:**
```
export const someListValues: ReadonlyArray<components["..."]["..."]["someList"]> = ["One", "Two", "Three"]
//  ^? const someListValues: readonly ("One" | "Two" | "Three")[][]
// See double square brackets
```
