### ISSUE TITLE
Incorrect type when using `prefixItems`

### ISSUE THREAD

**Issue by zyoshoka** [openapi-ts/openapi-typescript#1892]
**Description**

Using `prefixItems` generates incorrect type.

| Name                 | Version                      |
| :------------------- | :--------------------------- |
| `openapi-typescript` | `7.3.3`                      |
| Node.js              | `20.17.0`                      |

**Reproduction**

The following schema
```yaml
type: array
items:
  type: number
prefixItems:
  - number
  - number
```
generates incorrect type:
```ts
[number, number];
```

**Expected result**

This should generate open-tuple type according to JSON Schema 2020-12 draft[^1]:
```ts
[number, number, ...number[]];
```
and closed-tuple type should be generated[^2][^3] by
```yaml
type: array
items: false
prefixItems:
  - number
  - number
```
or
```yaml
type: array
unevaluatedItems: false
prefixItems:
  - number
  - number
```

[^1]: https://datatracker.ietf.org/doc/html/draft-bhutton-json-schema-01#name-prefixitems
[^2]: https://json-schema.org/draft/2020-12/release-notes#closed-tuple
[^3]: https://json-schema.org/understanding-json-schema/reference/array#unevaluateditems

**Checklist**

- [x] My OpenAPI schema passes the [Redocly validator](https://redocly.com/docs/cli/commands/lint/) (`npx @redocly/cli@latest lint`)
- [x] I’m willing to open a PR (see [CONTRIBUTING.md](https://github.com/openapi-ts/openapi-typescript/blob/main/packages/openapi-typescript/CONTRIBUTING.md))
