### ISSUE TITLE
openapi-typescript with custom redocly config runs forever

### ISSUE THREAD

**Issue by mithodin** [openapi-ts/openapi-typescript#1905]
**Description**

When invoking openapi-typescript with a custom redocly config, as documented [here](https://openapi-ts.dev/cli#multiple-schemas), it just runs forever without doing anything. There is no error message.

```
Paste full error message
```

| Name                 | Version                      |
| :------------------- | :--------------------------- |
| `openapi-typescript` | `7.4.0`                      |
| Node.js              | `18.17.1`                      |
| OS + version         | `Linux kernel 6.6.48_1` |

**Reproduction**
This is my redocly configuration:
```yaml
apis:
  pets@v1:
    root: https://petstore3.swagger.io/api/v3/openapi.yaml
    x-openapi-ts:
      output: ./src/api/pets.ts
```

**Checklist**

- [x] My OpenAPI schema passes the [Redocly validator](https://redocly.com/docs/cli/commands/lint/) (`npx @redocly/cli@latest lint`)
- [ ] I’m willing to open a PR (see [CONTRIBUTING.md](https://github.com/openapi-ts/openapi-typescript/blob/main/packages/openapi-typescript/CONTRIBUTING.md))

**Comment by oxisto** [comment]
I have a similar issue when using the new `--root-types` switch, I will try to investigate this further and provide an example / separate issue.

**Comment by yoshi2no** [comment]
@mithodin 

This might be off the mark, but is the file you created named `redocly.yaml` and placed at the root of the project? It seems that if the redocly file is not found and the input schema path is not specified with something like `npx openapi-typescript`, it defaults to running via stdin. I’ve confirmed that in such cases, it tries to process a Readable stream, but the process never completes.

**Comment by CallumJHays** [comment]
May be unrelated, but I ran into a similar issue from incorrectly including an `-i` flag: `openapi-typescript -i openapi.json` rather than just`openapi-typescript openapi.json`

**Comment by oxisto** [comment]
> May be unrelated, but I ran into a similar issue from incorrectly including an `-i` flag: `openapi-typescript -i openapi.json` rather than just`openapi-typescript openapi.json`

I also ran into a similar thing, it looks like if the parser arguments do not match or are in the wrong, then the command just hangs. Took me a while to finally figure out what was happening.

**Comment by CptJJ** [comment]
Running into the exact same issue, my file also passes `npx @redocly/cli@latest lint`

```
apis:
    authorization@v1:
        root: ./src/schemas/authorization.json
        x-openapi-ts:
            output: ./src/schemas/authorization.ts
    comprehensive-rate:
        root: ./src/schemas/comprehensive-rate.json
        x-openapi-ts:
            output: ./src/schemas/comprehensive-rate.ts
rules:
    no-ambiguous-paths: error
```
