### ISSUE TITLE
Unable to connect to non public schemas

### ISSUE THREAD

**Issue by emavitta** [openapi-ts/openapi-typescript#2018]
**Description**

Im trying to connect to a non public schema using a basic auth via `redocly.yaml` file for configuration, but i'm not able to do it.
Following the docs my first try was this

```
apis:
  auth@v1:
    root: https://non-public-schema.org/swagger/v1/swagger.json
    x-openapi-ts:
      output: ./openapi/auth.ts
resolve:
  http:
    - matches: https://non-public-schema.org/swagger/v1/swagger.json
      name: Authorization
      value: Basic SECRET_AUTH
```

but it gave me `unauthorized 401`

thenk i tried 

```
apis:
  auth@v1:
    root: https://non-public-schema.org/swagger/v1/swagger.json
    x-openapi-ts:
      output: ./openapi/auth.ts
  resolve:
    http:
      - matches: https://non-public-schema.org/swagger/v1/swagger.json
        name: Authorization
        value: Basic SECRET_AUTH
```

using the resolve inside the apis object

and the error now is 
```
Error: API resolve is missing an `x-openapi-ts.output` key. See https://openapi-ts.dev/cli/#multiple-schemas.
```

Am i missing something on how to configure the `redocly.yaml` file?

| Name                 | Version                      |
| :------------------- | :--------------------------- |
| `openapi-typescript` | `7.4.3`                      |
| Node.js              | `22.2.0`                      |
| OS + version         | `macOS 15.1.1` |
