### ISSUE TITLE
`--array-length` with `minItems: 1` generates empty array

### ISSUE THREAD

**Issue by OliverJAsh** [openapi-ts/openapi-typescript#2048]
**Description**

`--array-length` with `minItems: 1` generates empty array.

Tested with v7.4.4 and v7.1.2.

**Reproduction**

Copy the example here: https://openapi-ts.dev/cli#arraylength

```yaml
components:
  schemas:
    TupleType:
      type: array
      items:
        type: string
      minItems: 1
      maxItems: 2
```

**Expected result**

```ts
export interface components {
    schemas: {
        readonly TupleType: [string] | [string, string];
    };
}

```

**Actual result**

```ts
export interface components {
    schemas: {
        readonly TupleType: [
        ] | [
            string
        ];
    };
}

```

**Checklist**

- [ ] My OpenAPI schema passes the [Redocly validator](https://redocly.com/docs/cli/commands/lint/) (`npx @redocly/cli@latest lint`)
- [ ] I’m willing to open a PR (see [CONTRIBUTING.md](https://github.com/openapi-ts/openapi-typescript/blob/main/packages/openapi-typescript/CONTRIBUTING.md))

**Comment by duncanbeevers** [comment]
I've been poking at this implementation in order to fix this bug and came across what I think is unexpected behavior, making it impossible to generate heterogeneous array types.

Given this schema, here are the generated types.

```yaml
components:
  schemas:
    HeterogeneousArray:
      type: array
      items:
        - type: number
        - type: string
```

```ts
// Result type is [number, string], not [number | string]()
interface components = {
  schemas: {
    HeterogeneousArray: [number, string];
  }
};
```

Forgive me if I missed some discussion around this, but I thought for items in fixed positions it would be necessary to use the `prefixItems` portion of the OpenAPI schema, and that the primary `items` slot could be used to specify heterogeneous array member types.
