### ISSUE TITLE
Discriminated Union Not Typed Correctly

### ISSUE THREAD

**Issue by iulspop** [openapi-ts/openapi-typescript#2154]
### openapi-typescript version

7.6.1

### Node.js version

22.12.0

### OS + version

macOS 15.2

### Description

# Reproduce Bug

## Given

```yaml
    CreateRepositoryRequest:
      description: Lorem ipsum dolor sit amet.
      type: object
      discriminator:
        propertyName: type
        mapping:
          azure: '#/components/schemas/CreateAzureRepositoryRequest'
          git: '#/components/schemas/CreateGitRepositoryRequest'
```

## When

run `npm run generate`

## Actual

```ts
        CreateRepositoryRequest: Record<string, never>;
```

## Expected

A discriminated union of the two types, something like:
```ts
        "CreateRepositoryRequest": {
            type: "azure" | "git";
        } & ({
            type: "azure";
        } & components["schemas"]["CreateAzureRepositoryRequest"]) | ({
            type: "git";
        } & components["schemas"]["CreateGitRepositoryRequest"]);
```

### Reproduction

clone: https://github.com/iulspop/bug-report-openapi-typescript-feb-13-2025
then `npm i && npm run generate`

### Expected result

A discriminated union of the two types, something like:
```ts
        "CreateRepositoryRequest": {
            type: "azure" | "git";
        } & ({
            type: "azure";
        } & components["schemas"]["CreateAzureRepositoryRequest"]) | ({
            type: "git";
        } & components["schemas"]["CreateGitRepositoryRequest"]);
```

### Required

- [x] My OpenAPI schema is valid and passes the [Redocly validator](https://redocly.com/docs/cli/commands/lint/) (`npx @redocly/cli@latest lint`)

### Extra

- [x] I’m willing to open a PR (see [CONTRIBUTING.md](https://github.com/openapi-ts/openapi-typescript/blob/main/packages/openapi-typescript/CONTRIBUTING.md))
